const foreignCityData = [{
	cityName: "澳门",
	citySpell: "AOMEN",
	"code": "MFM",
	"countryCode": "MO",
	"countryName": "中国澳门",
	cityFirstLetter: "A"
}, {
	cityName: "阿姆斯特丹",
	citySpell: "AMUSITEDAN",
	"code": "AMS",
	"countryCode": "NL",
	"countryName": "荷兰",
	cityFirstLetter: "A"
}, {
	cityName: "爱丁堡",
	citySpell: "AIDINGBAO",
	"code": "EDI",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "A"
}, {
	cityName: "奥兰多",
	citySpell: "AOLANDUO",
	"code": "ORL",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "A"
}, {
	cityName: "奥克兰",
	citySpell: "AOKELAN",
	"code": "AKL",
	"countryCode": "NZ",
	"countryName": "新西兰",
	cityFirstLetter: "A"
}, {
	cityName: "阿德莱德",
	citySpell: "ADELAIDE",
	"code": "ADL",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "A"
}, {
	cityName: "阿布扎比",
	citySpell: "ABUZHABI",
	"code": "AUH",
	"countryCode": "AE",
	"countryName": "阿联酋",
	cityFirstLetter: "A"
}, {
	cityName: "巴黎",
	citySpell: "BALI",
	"code": "PAR",
	"countryCode": "FR",
	"countryName": "法国",
	cityFirstLetter: "B"
}, {
	cityName: "柏林",
	citySpell: "BOLIN",
	"code": "BER",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "B"
}, {
	cityName: "巴厘岛",
	citySpell: "BALIDAO",
	"code": "DPS",
	"countryCode": "ID",
	"countryName": "印度尼西亚",
	cityFirstLetter: "B"
}, {
	cityName: "布拉格",
	citySpell: "BULAGE",
	"code": "PRG",
	"countryCode": "CZ",
	"countryName": "捷克",
	cityFirstLetter: "B"
}, {
	cityName: "巴塞罗那",
	citySpell: "BASAILUONA",
	"code": "BCN",
	"countryCode": "ES",
	"countryName": "西班牙",
	cityFirstLetter: "B"
}, {
	cityName: "布里斯班",
	citySpell: "BULISIBAN",
	"code": "BNE",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "B"
}, {
	cityName: "波士顿",
	citySpell: "BOSHIDUN",
	"code": "BOS",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "B"
}, {
	cityName: "布鲁塞尔",
	citySpell: "BULUSAIER",
	"code": "BRU",
	"countryCode": "BE",
	"countryName": "比利时",
	cityFirstLetter: "B"
}, {
	cityName: "伯明翰",
	citySpell: "BOMINGHAN",
	"code": "BHX",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "B"
}, {
	cityName: "布达佩斯",
	citySpell: "BUDAPEISI",
	"code": "BUD",
	"countryCode": "HU",
	"countryName": "匈牙利",
	cityFirstLetter: "B"
}, {
	cityName: "波特兰",
	citySpell: "BOTELAN",
	"code": "PTJ",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "B"
}, {
	cityName: "布宜诺斯艾利斯",
	citySpell: "BUYINUOSIAILISI",
	"code": "BUE",
	"countryCode": "AR",
	"countryName": "阿根廷",
	cityFirstLetter: "B"
}, {
	cityName: "不来梅",
	citySpell: "BULAIMEI",
	"code": "BRE",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "B"
}, {
	cityName: "大阪",
	citySpell: "DABAN",
	"code": "OSA",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "D"
}, {
	cityName: "东京",
	citySpell: "DONGJING",
	"code": "TYO",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "D"
}, {
	cityName: "迪拜",
	citySpell: "DIBAI",
	"code": "DXB",
	"countryCode": "AE",
	"countryName": "阿联酋",
	cityFirstLetter: "D"
}, {
	cityName: "达拉斯",
	citySpell: "DALASI",
	"code": "DFW",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "D"
}, {
	cityName: "多伦多",
	citySpell: "DUOLUNDUO",
	"code": "YTO",
	"countryCode": "CA",
	"countryName": "加拿大",
	cityFirstLetter: "D"
}, {
	cityName: "丹佛",
	citySpell: "DANFO",
	"code": "DEN",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "D"
}, {
	cityName: "底特律",
	citySpell: "DITELV",
	"code": "DTT",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "D"
}, {
	cityName: "达尔文",
	citySpell: "DAERWEN",
	"code": "DRW",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "D"
}, {
	cityName: "都灵",
	citySpell: "DOULING",
	"code": "TRN",
	"countryCode": "IT",
	"countryName": "意大利",
	cityFirstLetter: "D"
}, {
	cityName: "都柏林",
	citySpell: "DOUBAILIN",
	"code": "DUB",
	"countryCode": "IE",
	"countryName": "爱尔兰",
	cityFirstLetter: "D"
}, {
	cityName: "杜塞尔多夫",
	citySpell: "DUSAIERDUOFU",
	"code": "DUS",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "D"
}, {
	cityName: "达尼丁",
	citySpell: "DANIDING",
	"code": "DUD",
	"countryCode": "NZ",
	"countryName": "新西兰",
	cityFirstLetter: "D"
}, {
	cityName: "法兰克福",
	citySpell: "FALANKEFU",
	"code": "FRA",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "F"
}, {
	cityName: "釜山",
	citySpell: "FUSHAN",
	"code": "PUS",
	"countryCode": "KR",
	"countryName": "韩国",
	cityFirstLetter: "F"
}, {
	cityName: "福冈",
	citySpell: "FUGANG",
	"code": "FUK",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "F"
}, {
	cityName: "费城",
	citySpell: "FEICHENG",
	"code": "PHL",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "F"
}, {
	cityName: "佛罗伦萨",
	citySpell: "FOLUOLUNSA",
	"code": "FLR",
	"countryCode": "IT",
	"countryName": "意大利",
	cityFirstLetter: "F"
}, {
	cityName: "凤凰城",
	citySpell: "FENGHUANGCHENG",
	"code": "PHX",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "F"
}, {
	cityName: "富山",
	citySpell: "FUSHAN",
	"code": "TOY",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "F"
}, {
	cityName: "富勒顿",
	citySpell: "FULEDUN",
	"code": "FUL",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "F"
}, {
	cityName: "广岛",
	citySpell: "GUANGDAO",
	"code": "HIJ",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "G"
}, {
	cityName: "高雄",
	citySpell: "GAOXIONG",
	"code": "KHH",
	"countryCode": "TW",
	"countryName": "中国台湾",
	cityFirstLetter: "G"
}, {
	cityName: "哥本哈根",
	citySpell: "GEBENHAGEN",
	"code": "CPH",
	"countryCode": "DK",
	"countryName": "丹麦",
	cityFirstLetter: "G"
}, {
	cityName: "格拉斯哥",
	citySpell: "GELASIGE",
	"code": "GLA",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "G"
}, {
	cityName: "胡志明市",
	citySpell: "HUZHIMINGSHI",
	"code": "SGN",
	"countryCode": "VN",
	"countryName": "越南",
	cityFirstLetter: "H"
}, {
	cityName: "河内",
	citySpell: "HENEI",
	"code": "HAN",
	"countryCode": "VN",
	"countryName": "越南",
	cityFirstLetter: "H"
}, {
	cityName: "华盛顿",
	citySpell: "HUASHENGDUN",
	"code": "WAS",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "H"
}, {
	cityName: "赫尔辛基",
	citySpell: "HEERXINJI",
	"code": "HEL",
	"countryCode": "FI",
	"countryName": "芬兰",
	cityFirstLetter: "H"
}, {
	cityName: "汉堡",
	citySpell: "HANBAO",
	"code": "HAM",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "H"
}, {
	cityName: "华沙",
	citySpell: "HUASHA",
	"code": "WAW",
	"countryCode": "PL",
	"countryName": "波兰",
	cityFirstLetter: "H"
}, {
	cityName: "惠灵顿",
	citySpell: "HUILINGDUN",
	"code": "WLG",
	"countryCode": "NZ",
	"countryName": "新西兰",
	cityFirstLetter: "H"
}, {
	cityName: "函馆",
	citySpell: "HANGUAN",
	"code": "HKD",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "H"
}, {
	cityName: "黄金海岸",
	citySpell: "HUANGJINHAIAN",
	"code": "OOL",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "H"
}, {
	cityName: "吉隆坡",
	citySpell: "JILONGPO",
	"code": "KUL",
	"countryCode": "MY",
	"countryName": "马来西亚",
	cityFirstLetter: "J"
}, {
	cityName: "济州岛",
	citySpell: "JIZHOUDAO",
	"code": "CJU",
	"countryCode": "KR",
	"countryName": "韩国",
	cityFirstLetter: "J"
}, {
	cityName: "金边",
	citySpell: "JINBIAN",
	"code": "PNH",
	"countryCode": "KH",
	"countryName": "柬埔寨",
	cityFirstLetter: "J"
}, {
	cityName: "加德满都",
	citySpell: "JIADEMANDU",
	"code": "KTM",
	"countryCode": "NP",
	"countryName": "尼泊尔",
	cityFirstLetter: "J"
}, {
	cityName: "旧金山",
	citySpell: "JIUJINSHAN",
	"code": "SFO",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "J"
}, {
	cityName: "静冈",
	citySpell: "JINGGANG",
	"code": "FSZ",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "J"
}, {
	cityName: "京都",
	citySpell: "JINGDOU",
	"code": "UKY",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "J"
}, {
	cityName: "基督城",
	citySpell: "JIDUCHENG",
	"code": "CHC",
	"countryCode": "NZ",
	"countryName": "新西兰",
	cityFirstLetter: "J"
}, {
	cityName: "甲米",
	citySpell: "JIAMI",
	"code": "KBV",
	"countryCode": "TH",
	"countryName": "泰国",
	cityFirstLetter: "J"
}, {
	cityName: "基辅",
	citySpell: "JIFU",
	"code": "IEV",
	"countryCode": "UA",
	"countryName": "乌克兰",
	cityFirstLetter: "J"
}, {
	cityName: "堪培拉",
	citySpell: "KANPEILA",
	"code": "CBR",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "K"
}, {
	cityName: "开罗",
	citySpell: "KAILUO",
	"code": "CAI",
	"countryCode": "EG",
	"countryName": "埃及",
	cityFirstLetter: "K"
}, {
	cityName: "开普敦",
	citySpell: "KAIPUDUN",
	"code": "CPT",
	"countryCode": "ZA",
	"countryName": "南非",
	cityFirstLetter: "K"
}, {
	cityName: "洛杉矶",
	citySpell: "LUOSHANJI",
	"code": "LAX",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "L"
}, {
	cityName: "伦敦",
	citySpell: "LUNDUN",
	"code": "LON",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "L"
}, {
	cityName: "罗马",
	citySpell: "LUOMA",
	"code": "ROM",
	"countryCode": "IT",
	"countryName": "意大利",
	cityFirstLetter: "L"
}, {
	cityName: "拉斯维加斯",
	citySpell: "LASIWEIJIASI",
	"code": "LAS",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "L"
}, {
	cityName: "曼谷",
	citySpell: "MANGU",
	"code": "BKK",
	"countryCode": "TH",
	"countryName": "泰国",
	cityFirstLetter: "M"
}, {
	cityName: "马尼拉",
	citySpell: "MANILA",
	"code": "MNL",
	"countryCode": "PH",
	"countryName": "菲律宾",
	cityFirstLetter: "M"
}, {
	cityName: "莫斯科",
	citySpell: "MOSIKE",
	"code": "MOW",
	"countryCode": "RU",
	"countryName": "俄罗斯",
	cityFirstLetter: "M"
}, {
	cityName: "墨尔本",
	citySpell: "MOERBEN",
	"code": "MEL",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "M"
}, {
	cityName: "马累",
	citySpell: "MALEI",
	"code": "MLE",
	"countryCode": "MV",
	"countryName": "马尔代夫",
	cityFirstLetter: "M"
}, {
	cityName: "曼彻斯特(英国)",
	citySpell: "MANCHESITE",
	"code": "MAN",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "M"
}, {
	cityName: "名古屋",
	citySpell: "MINGGUWU",
	"code": "NGO",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "M"
}, {
	cityName: "墨尔本",
	citySpell: "MOERBEN",
	"code": "MLB",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "M"
}, {
	cityName: "马德里",
	citySpell: "MADELI",
	"code": "MAD",
	"countryCode": "ES",
	"countryName": "西班牙",
	cityFirstLetter: "M"
}, {
	cityName: "孟买",
	citySpell: "MENGMAI",
	"code": "BOM",
	"countryCode": "IN",
	"countryName": "印度",
	cityFirstLetter: "M"
}, {
	cityName: "慕尼黑",
	citySpell: "MUNIHEI",
	"code": "MUC",
	"countryCode": "DE",
	"countryName": "德国",
	cityFirstLetter: "M"
}, {
	cityName: "米兰",
	citySpell: "MILAN",
	"code": "MIL",
	"countryCode": "IT",
	"countryName": "意大利",
	cityFirstLetter: "M"
}, {
	cityName: "迈阿密",
	citySpell: "MAIAMI",
	"code": "MIA",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "M"
}, {
	cityName: "孟菲斯",
	citySpell: "MENGFEISI",
	"code": "MEM",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "M"
}, {
	cityName: "蒙特利尔",
	citySpell: "MENGTELIER",
	"code": "YMQ",
	"countryCode": "CA",
	"countryName": "加拿大",
	cityFirstLetter: "M"
}, {
	cityName: "明尼阿波利斯",
	citySpell: "MINGNIABOLISI",
	"code": "MSP",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "M"
}, {
	cityName: "墨西哥城",
	citySpell: "MOXIGECHENG",
	"code": "MEX",
	"countryCode": "MX",
	"countryName": "墨西哥",
	cityFirstLetter: "M"
}, {
	cityName: "纽卡斯尔",
	citySpell: "NIUKASIER",
	"code": "NCL",
	"countryCode": "GB",
	"countryName": "英国",
	cityFirstLetter: "N"
}, {
	cityName: "纽约",
	citySpell: "NIUYUE",
	"code": "NYC",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "N"
}, {
	cityName: "内罗毕",
	citySpell: "NEILUOBI",
	"code": "NBO",
	"countryCode": "KE",
	"countryName": "肯尼亚",
	cityFirstLetter: "N"
}, {
	cityName: "普吉岛",
	citySpell: "PUJIDAO",
	"code": "HKT",
	"countryCode": "TH",
	"countryName": "泰国",
	cityFirstLetter: "P"
}, {
	cityName: "日内瓦",
	citySpell: "RINEIWA",
	"code": "GVA",
	"countryCode": "CH",
	"countryName": "瑞士",
	cityFirstLetter: "R"
}, {
	cityName: "首尔",
	citySpell: "SHOUER",
	"code": "SEL",
	"countryCode": "KR",
	"countryName": "韩国",
	cityFirstLetter: "S"
}, {
	cityName: "斯德哥尔摩",
	citySpell: "SIDEGEERMO",
	"code": "STO",
	"countryCode": "SE",
	"countryName": "瑞典",
	cityFirstLetter: "S"
}, {
	cityName: "塞班",
	citySpell: "SAIBAN",
	"code": "SPN",
	"countryCode": "MP",
	"countryName": "北马里亚纳群岛",
	cityFirstLetter: "S"
}, {
	cityName: "塞维利亚",
	citySpell: "SAIWEILIYA",
	"code": "SVQ",
	"countryCode": "ES",
	"countryName": "西班牙",
	cityFirstLetter: "S"
}, {
	cityName: "圣保罗",
	citySpell: "SHENGBAOLUO",
	"code": "SAO",
	"countryCode": "BR",
	"countryName": "巴西",
	cityFirstLetter: "S"
}, {
	cityName: "苏黎世",
	citySpell: "SULISHI",
	"code": "ZRH",
	"countryCode": "CH",
	"countryName": "瑞士",
	cityFirstLetter: "S"
}, {
	cityName: "苏梅岛",
	citySpell: "SUMEIDAO",
	"code": "USM",
	"countryCode": "TH",
	"countryName": "泰国",
	cityFirstLetter: "S"
}, {
	cityName: "圣彼得堡",
	citySpell: "SHENGBIDEBAO",
	"code": "LED",
	"countryCode": "RU",
	"countryName": "俄罗斯",
	cityFirstLetter: "S"
}, {
	cityName: "圣何塞",
	citySpell: "SHENGHESAI",
	"code": "SJO",
	"countryCode": "CR",
	"countryName": "哥斯达黎加",
	cityFirstLetter: "S"
}, {
	cityName: "台北",
	citySpell: "TAIBEI",
	"code": "TPE",
	"countryCode": "TW",
	"countryName": "中国台湾",
	cityFirstLetter: "T"
}, {
	cityName: "突尼斯",
	citySpell: "TUNISI",
	"code": "TUN",
	"countryCode": "TN",
	"countryName": "突尼斯",
	cityFirstLetter: "T"
}, {
	cityName: "台东",
	citySpell: "TAIDONG",
	"code": "TTT",
	"countryCode": "TW",
	"countryName": "中国台湾",
	cityFirstLetter: "T"
}, {
	cityName: "乌兰巴托",
	citySpell: "WULANBATUO",
	"code": "ULN",
	"countryCode": "MN",
	"countryName": "蒙古",
	cityFirstLetter: "W"
}, {
	cityName: "温哥华",
	citySpell: "WENGEHUA",
	"code": "YVR",
	"countryCode": "CA",
	"countryName": "加拿大",
	cityFirstLetter: "W"
}, {
	cityName: "维也纳",
	citySpell: "WEIYENA",
	"code": "VIE",
	"countryCode": "AT",
	"countryName": "奥地利",
	cityFirstLetter: "W"
}, {
	cityName: "威尼斯",
	citySpell: "WEINISI",
	"code": "VCE",
	"countryCode": "IT",
	"countryName": "意大利",
	cityFirstLetter: "W"
}, {
	cityName: "渥太华",
	citySpell: "WOTAIHUA",
	"code": "YOW",
	"countryCode": "CA",
	"countryName": "加拿大",
	cityFirstLetter: "W"
}, {
	cityName: "香港",
	citySpell: "XIANGGANG",
	"code": "HKG",
	"countryCode": "HK",
	"countryName": "中国香港",
	cityFirstLetter: "X"
}, {
	cityName: "新加坡",
	citySpell: "XINJIAPO",
	"code": "SIN",
	"countryCode": "SG",
	"countryName": "新加坡",
	cityFirstLetter: "X"
}, {
	cityName: "悉尼",
	citySpell: "XINI",
	"code": "SYD",
	"countryCode": "AU",
	"countryName": "澳大利亚",
	cityFirstLetter: "X"
}, {
	cityName: "新德里",
	citySpell: "XINDELI",
	"code": "DEL",
	"countryCode": "IN",
	"countryName": "印度",
	cityFirstLetter: "X"
}, {
	cityName: "休斯敦",
	citySpell: "XIUSIDUN",
	"code": "HOU",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "X"
}, {
	cityName: "西雅图",
	citySpell: "XIYATU",
	"code": "SEA",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "X"
}, {
	cityName: "新奥尔良",
	citySpell: "XINAOERLIANG",
	"code": "MSY",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "X"
}, {
	cityName: "新泻",
	citySpell: "XINXIE",
	"code": "KIJ",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "X"
}, {
	cityName: "仙台",
	citySpell: "XIANTAI",
	"code": "SDJ",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "X"
}, {
	cityName: "雅加达",
	citySpell: "YAJIADA",
	"code": "JKT",
	"countryCode": "ID",
	"countryName": "印度尼西亚",
	cityFirstLetter: "Y"
}, {
	cityName: "雅典",
	citySpell: "YADIAN",
	"code": "ATH",
	"countryCode": "GR",
	"countryName": "希腊",
	cityFirstLetter: "Y"
}, {
	cityName: "亚特兰大",
	citySpell: "YATELANDA",
	"code": "ATL",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "Y"
}, {
	cityName: "伊斯兰堡",
	citySpell: "YISILANBAO",
	"code": "ISB",
	"countryCode": "PK",
	"countryName": "巴基斯坦",
	cityFirstLetter: "Y"
}, {
	cityName: "仰光",
	citySpell: "YANGGUANG",
	"code": "RGN",
	"countryCode": "MM",
	"countryName": "缅甸",
	cityFirstLetter: "Y"
}, {
	cityName: "伊斯坦布尔",
	citySpell: "YISITANBUER",
	"code": "IST",
	"countryCode": "TR",
	"countryName": "土耳其",
	cityFirstLetter: "Y"
}, {
	cityName: "盐湖城",
	citySpell: "YANHUCHENG",
	"code": "SLC",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "Y"
}, {
	cityName: "约翰内斯堡",
	citySpell: "YUEHANNEISIBAO",
	"code": "JNB",
	"countryCode": "ZA",
	"countryName": "南非",
	cityFirstLetter: "Y"
}, {
	cityName: "札幌",
	citySpell: "ZHAHUANG",
	"code": "SPK",
	"countryCode": "JP",
	"countryName": "日本",
	cityFirstLetter: "Z"
}, {
	cityName: "芝加哥",
	citySpell: "ZHIJIAGE",
	"code": "CHI",
	"countryCode": "US",
	"countryName": "美国",
	cityFirstLetter: "Z"
}]
export default foreignCityData